import { useState } from 'react';
import { motion, AnimatePresence } from 'framer-motion';
import { ChevronDown } from 'lucide-react';
import { SectionBackground } from '../components/SectionBackground';
import { SukunaSlideshow } from '../components/SukunaSlideshow';

const FAQS = [
  {
    q: "Is the bot free to use?",
    a: "There is a free tier with limited commands available for casual users. Premium plans unlock all advanced features, AI capabilities, and eliminate usage limits."
  },
  {
    q: "Will my WhatsApp account get banned?",
    a: "We use the official WhatsApp multi-device pairing method (the same used by WhatsApp Web). While the risk is minimal compared to older methods, aggressive spamming or violating WhatsApp's TOS can still lead to bans. Use power features responsibly."
  },
  {
    q: "What is a pairing code?",
    a: "A pairing code is a secure 8-digit sequence generated by our servers that links your WhatsApp number to the bot. It replaces the need to scan a QR code with a secondary device, allowing you to pair directly from your phone."
  },
  {
    q: "Can I run the bot on multiple numbers?",
    a: "Yes! The Empire tier supports multi-device and multi-session configurations, allowing you to manage several numbers from a single dashboard."
  },
  {
    q: "How do I stop or disconnect the bot?",
    a: "You have complete control. To disconnect, simply open WhatsApp on your phone, go to Linked Devices, and tap 'Remove Device' for the bot's session. It will instantly terminate."
  },
  {
    q: "What platforms does the media downloader support?",
    a: "The built-in downloader currently supports extracting media from YouTube, TikTok (without watermark), Instagram (Reels, Posts, Stories), Twitter/X, Facebook, and Spotify."
  }
];

export function FAQ() {
  const [openIndex, setOpenIndex] = useState<number | null>(0);

  return (
    <div className="min-h-screen pt-24 pb-16">
      <SectionBackground className="py-8" withSukunaBackground>
        <div className="container mx-auto px-4 max-w-3xl">

          <div className="text-center mb-16">
            <motion.h1
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              className="text-4xl md:text-5xl font-cinzel font-bold text-white mb-4 text-glow"
            >
              FREQUENTLY ASKED
            </motion.h1>
            <p className="text-white/60 text-lg">Knowledge is power. Equip yourself.</p>
          </div>

          <div className="mb-12">
            <SukunaSlideshow interval={30000} variant="gallery" />
          </div>

          <div className="space-y-4">
            {FAQS.map((faq, index) => (
              <motion.div
                key={index}
                initial={{ opacity: 0, y: 10 }}
                animate={{ opacity: 1, y: 0 }}
                transition={{ delay: index * 0.1 }}
                className="glass-card rounded-lg overflow-hidden"
              >
                <button
                  onClick={() => setOpenIndex(openIndex === index ? null : index)}
                  className="w-full text-left px-6 py-5 flex justify-between items-center hover:bg-white/[0.05] transition-colors"
                >
                  <span className="font-bold text-white pr-8">{faq.q}</span>
                  <ChevronDown
                    className={`text-primary shrink-0 transition-transform duration-300 ${openIndex === index ? 'rotate-180' : ''}`}
                  />
                </button>

                <AnimatePresence>
                  {openIndex === index && (
                    <motion.div
                      initial={{ height: 0, opacity: 0 }}
                      animate={{ height: "auto", opacity: 1 }}
                      exit={{ height: 0, opacity: 0 }}
                      transition={{ duration: 0.3 }}
                      className="overflow-hidden"
                    >
                      <div className="px-6 pb-5 pt-0 text-white/60 leading-relaxed">
                        <div className="h-px w-full bg-white/5 mb-4"></div>
                        {faq.a}
                      </div>
                    </motion.div>
                  )}
                </AnimatePresence>
              </motion.div>
            ))}
          </div>

          <div className="mt-16 text-center p-8 border border-white/5 rounded-lg glass">
            <p className="text-white font-bold mb-2">Still have questions?</p>
            <p className="text-white/60 mb-4">Join our Discord community for direct support from the developers.</p>
            <button className="px-6 py-2 bg-primary/20 text-primary border border-primary/50 rounded hover:bg-primary hover:text-white transition-all">
              Join Discord
            </button>
          </div>

        </div>
      </SectionBackground>
    </div>
  );
}
